name: Build and Deploy Angular + Spring Boot

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the code
      - name: Checkout repo
        uses: actions/checkout@v3

      # 2. Set up Node.js for Angular
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      # 3. Build Angular frontend
      - name: Build Angular
        run: |
          cd frontend
          npm install
          npm run build --prod

      # 4. Copy Angular build to Spring Boot static folder
      - name: Copy Angular build to backend
        run: |
          cp -r frontend/dist/built/* backend/src/main/resources/static/

      # 5. Set up Java for Spring Boot
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '17'

      # 6. Build Spring Boot backend
      - name: Build Spring Boot
        run: mvn clean package -DskipTests
        working-directory: ./backend

      # 7. Login to Azure
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # 8. Deploy JAR to Azure Web App
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ secrets.AZURE_WEBAPP_NAME_BACKEND }}
          package: ./backend/target/demo10-0.0.1-SNAPSHOT.jar
