name: Build and Deploy Backend

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Login to Azure
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Step 3: Build backend Docker image
      - name: Build Docker Image
        run: |
          cd backend
          docker build -t ${{ secrets.AZURE_WEBAPP_NAME_BACKEND }}:latest .

      # Step 4: Push & Deploy to Azure Web App
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ secrets.AZURE_WEBAPP_NAME_BACKEND }}
          images: ${AZURE_WEBAPP_NAME_BACKEND}:latest
          slot-name: production
